"""add school_id to textbooks and materials

Revision ID: 1905c2328b0c
Revises: 83fa8d74116e
Create Date: 2026-05-25 16:49:19.967212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1905c2328b0c'
down_revision: Union[str, None] = '83fa8d74116e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_absence_reports')
    with op.batch_alter_table('absence_reports', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('master_textbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('_subject_level_book_uc'), type_='unique')
        batch_op.create_unique_constraint('_subject_level_book_scope_uc', ['subject', 'level', 'book_name', 'tenant_id', 'school_id'])
        batch_op.create_foreign_key('fk_textbook_school', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_textbook_tenant', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('root_tables', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('student_report_states', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('teaching_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_foreign_key('fk_material_school', 'schools', ['school_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('teaching_materials', schema=None) as batch_op:
        batch_op.drop_constraint('fk_material_school', type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('school_id')

    with op.batch_alter_table('student_report_states', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('root_tables', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('master_textbooks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_textbook_school', type_='foreignkey')
        batch_op.drop_constraint('fk_textbook_tenant', type_='foreignkey')
        batch_op.drop_constraint('_subject_level_book_scope_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_subject_level_book_uc'), ['subject', 'level', 'book_name'])
        batch_op.drop_column('school_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('absence_reports', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    op.create_table('_alembic_tmp_absence_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('instructor_id', sa.INTEGER(), nullable=False),
    sa.Column('absence_date', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('report_info', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
