"""add tenant customization models

Revision ID: 238a2cd07d13
Revises: befc911f79af
Create Date: 2026-06-11 15:29:26.248904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238a2cd07d13'
down_revision: Union[str, None] = 'befc911f79af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_username', sa.String(), nullable=False),
    sa.Column('report_date', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bug_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bug_reports_id'), ['id'], unique=False)

    op.create_table('changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('changelog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changelog_id'), ['id'], unique=False)

    op.create_table('detail_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detail_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detail_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detail_tags_name'), ['name'], unique=True)

    op.create_table('feature_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_username', sa.String(), nullable=False),
    sa.Column('report_date', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_requests_id'), ['id'], unique=False)

    op.create_table('root_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('root_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_root_tables_id'), ['id'], unique=False)

    op.create_table('subject_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_tags_name'), ['name'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('announcement_enabled', sa.Boolean(), nullable=True),
    sa.Column('announcement_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_id'), ['id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_name'), ['name'], unique=True)

    op.create_table('route_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('graph_line_type', sa.String(), nullable=False),
    sa.Column('show_on_graph', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_levels_id'), ['id'], unique=False)

    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='_tenant_school_name_uc')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_id'), ['id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='_tenant_subject_name_uc')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_id'), ['id'], unique=False)

    op.create_table('tenant_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('duration_slope_formula', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_settings_id'), ['id'], unique=False)

    op.create_table('bulk_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('preset_name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject', 'preset_name', 'tenant_id', 'school_id', name='_subject_preset_scope_uc')
    )
    with op.batch_alter_table('bulk_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_presets_id'), ['id'], unique=False)

    op.create_table('master_textbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject', 'level', 'book_name', 'tenant_id', 'school_id', name='_subject_level_book_scope_uc')
    )
    with op.batch_alter_table('master_textbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_textbooks_id'), ['id'], unique=False)

    op.create_table('teaching_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('internal_memo', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), server_default='material', nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_materials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_materials_title'), ['title'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('bulk_preset_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['bulk_presets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_preset_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_preset_books_id'), ['id'], unique=False)

    op.create_table('material_detail_association',
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['detail_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['teaching_materials.id'], ondelete='CASCADE')
    )
    op.create_table('material_subject_association',
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['teaching_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject_tags.id'], ondelete='CASCADE')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('deviation_value', sa.Float(), nullable=True),
    sa.Column('target_level', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('previous_school', sa.String(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('shared_memo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='_school_id_name_uc')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)

    op.create_table('absence_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('absence_date', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('report_info', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('absence_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absence_reports_id'), ['id'], unique=False)

    op.create_table('eiken_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('cse_score', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eiken_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eiken_results_id'), ['id'], unique=False)

    op.create_table('mock_exam_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.String(), nullable=False),
    sa.Column('mock_exam_name', sa.String(), nullable=False),
    sa.Column('mock_exam_format', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('round', sa.String(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('subject_kokugo_desc', sa.Integer(), nullable=True),
    sa.Column('subject_math_desc', sa.Integer(), nullable=True),
    sa.Column('subject_english_desc', sa.Integer(), nullable=True),
    sa.Column('subject_rika1_desc', sa.Integer(), nullable=True),
    sa.Column('subject_rika2_desc', sa.Integer(), nullable=True),
    sa.Column('subject_shakai1_desc', sa.Integer(), nullable=True),
    sa.Column('subject_shakai2_desc', sa.Integer(), nullable=True),
    sa.Column('subject_kokugo_mark', sa.Integer(), nullable=True),
    sa.Column('subject_math1a_mark', sa.Integer(), nullable=True),
    sa.Column('subject_math2bc_mark', sa.Integer(), nullable=True),
    sa.Column('subject_english_r_mark', sa.Integer(), nullable=True),
    sa.Column('subject_english_l_mark', sa.Integer(), nullable=True),
    sa.Column('subject_rika1_mark', sa.Integer(), nullable=True),
    sa.Column('subject_rika2_mark', sa.Integer(), nullable=True),
    sa.Column('subject_shakai1_mark', sa.Integer(), nullable=True),
    sa.Column('subject_shakai2_mark', sa.Integer(), nullable=True),
    sa.Column('subject_rika_kiso1_mark', sa.Integer(), nullable=True),
    sa.Column('subject_rika_kiso2_mark', sa.Integer(), nullable=True),
    sa.Column('subject_info_mark', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mock_exam_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mock_exam_results_id'), ['id'], unique=False)

    op.create_table('past_exam_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('university_name', sa.String(), nullable=False),
    sa.Column('faculty_name', sa.String(), nullable=True),
    sa.Column('exam_system', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('time_required', sa.Integer(), nullable=True),
    sa.Column('total_time_allowed', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('past_exam_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_past_exam_results_id'), ['id'], unique=False)

    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('is_planned', sa.Boolean(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('completed_units', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject', 'level', 'book_name', name='_student_prog_uc')
    )
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_id'), ['id'], unique=False)

    op.create_table('student_instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'user_id', name='_student_user_uc')
    )
    with op.batch_alter_table('student_instructors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_instructors_id'), ['id'], unique=False)

    op.create_table('student_report_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_report_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_report_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_report_states_student_id'), ['student_id'], unique=True)

    op.create_table('transfer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('original_date', sa.String(), nullable=True),
    sa.Column('candidate_dates', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_date', sa.String(), nullable=True),
    sa.Column('instructor_comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_requests_id'), ['id'], unique=False)

    op.create_table('university_acceptance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('university_name', sa.String(), nullable=False),
    sa.Column('faculty_name', sa.String(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('exam_system', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('application_deadline', sa.String(), nullable=True),
    sa.Column('exam_date', sa.String(), nullable=True),
    sa.Column('announcement_date', sa.String(), nullable=True),
    sa.Column('procedure_deadline', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('university_acceptance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_university_acceptance_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_acceptance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_university_acceptance_id'))

    op.drop_table('university_acceptance')
    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_requests_id'))

    op.drop_table('transfer_requests')
    with op.batch_alter_table('student_report_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_report_states_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_report_states_id'))

    op.drop_table('student_report_states')
    with op.batch_alter_table('student_instructors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_instructors_id'))

    op.drop_table('student_instructors')
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_id'))

    op.drop_table('progress')
    with op.batch_alter_table('past_exam_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_past_exam_results_id'))

    op.drop_table('past_exam_results')
    with op.batch_alter_table('mock_exam_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mock_exam_results_id'))

    op.drop_table('mock_exam_results')
    with op.batch_alter_table('eiken_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eiken_results_id'))

    op.drop_table('eiken_results')
    with op.batch_alter_table('absence_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_reports_id'))

    op.drop_table('absence_reports')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_id'))

    op.drop_table('students')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    op.drop_table('material_subject_association')
    op.drop_table('material_detail_association')
    with op.batch_alter_table('bulk_preset_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_preset_books_id'))

    op.drop_table('bulk_preset_books')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_branch_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('teaching_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_materials_title'))
        batch_op.drop_index(batch_op.f('ix_teaching_materials_id'))

    op.drop_table('teaching_materials')
    with op.batch_alter_table('master_textbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_textbooks_id'))

    op.drop_table('master_textbooks')
    with op.batch_alter_table('bulk_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_presets_id'))

    op.drop_table('bulk_presets')
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_settings_id'))

    op.drop_table('tenant_settings')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_id'))

    op.drop_table('schools')
    with op.batch_alter_table('route_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_levels_id'))

    op.drop_table('route_levels')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_name'))
        batch_op.drop_index(batch_op.f('ix_tenants_id'))

    op.drop_table('tenants')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_id'))

    op.drop_table('system_settings')
    with op.batch_alter_table('subject_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_tags_name'))
        batch_op.drop_index(batch_op.f('ix_subject_tags_id'))

    op.drop_table('subject_tags')
    with op.batch_alter_table('root_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_root_tables_id'))

    op.drop_table('root_tables')
    with op.batch_alter_table('feature_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_requests_id'))

    op.drop_table('feature_requests')
    with op.batch_alter_table('detail_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detail_tags_name'))
        batch_op.drop_index(batch_op.f('ix_detail_tags_id'))

    op.drop_table('detail_tags')
    with op.batch_alter_table('changelog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changelog_id'))

    op.drop_table('changelog')
    with op.batch_alter_table('bug_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bug_reports_id'))

    op.drop_table('bug_reports')
    # ### end Alembic commands ###
