"""add sequence_order to subjects

Revision ID: 723c009f6c23
Revises: 5a76f252a168
Create Date: 2026-06-13 23:13:14.635705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723c009f6c23'
down_revision: Union[str, None] = '5a76f252a168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_order', sa.Integer(), server_default='0', nullable=False))  

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('sequence_order')

    # ### end Alembic commands ###
