"""add_target_grade_to_eiken

Revision ID: b182ab08eb9b
Revises: be3accb04673
Create Date: 2026-07-01 16:08:57.598276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b182ab08eb9b'
down_revision: Union[str, None] = 'be3accb04673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('eiken_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_grade', sa.String(), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('eiken_results', schema=None) as batch_op:
        batch_op.drop_column('target_grade')

    # ### end Alembic commands ###
